sonar.projectKey=wonder
sonar.projectName=wonder
sonar.sourceEncoding=UTF-8
sonar.sources=controllers,models,routes,middleware,utils
sonar.host.url=http://localhost:9000
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/uploads/**
sonar.token=sqp_faf4d7641270abec62b400cc837dc33ad25c48b2
sonar.javascript.lcov.reportPaths=coverage/lcov.info