sonar.projectKey=wonder
sonar.projectName=wonder
sonar.sourceEncoding=UTF-8
sonar.sources=controllers,models,routes,middleware,utils
sonar.host.url=http://localhost:9000
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/uploads/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info